### ISSUE TITLE
Install jekyll-compose gem

### ISSUE THREAD

**Issue by nmenag** [mattvh/jekyllthemes#137]
View gem https://github.com/jekyll/jekyll-compose

**Comment by jacobtomlinson** [comment]
Is this a request?

**Comment by nmenag** [comment]
yes, but Is this helpful for the project?

**Comment by jacobtomlinson** [comment]
I think this project assumes that people have `jekyll` installed globally. It doesn't actually have a `Gemfile`. In which case it should probably be left for people to install `jekyll-compose` globally.

**Comment by nmenag** [comment]
you must create a `Gemfile` file  with this structure: 

```ruby
source 'https://rubygems.org'
gem 'jekyll'
group :jekyll_plugins do
  gem 'jekyll-compose'
end
````

**Comment by gynter** [comment]
@nmenag why is this gem needed?

**Comment by jacobtomlinson** [comment]
I think this gem is to help authoring. However as it is probably more of a personal preference and this repo is authored by many people it shouldn't be added.

**Comment by nmenag** [comment]
Ok, then close issue.
