### ISSUE TITLE
DevAid download is broken

### ISSUE THREAD

**Issue by gynter** [mattvh/jekyllthemes#141]
From the sources the correct one should be <https://github.com/kevit/devaid-jekyll-theme/archive/master.zip>?

**Comment by geraldb** [comment]
@gynter  I invite you (agian) to flag the errors at the new alternative Dr. Jekyll's Themes site.  All themes are listed in the [themes.yml](https://github.com/drjekyllthemes/drjekyllthemes.github.io/blob/master/_data/themes.yml) datafile. Any help appreciated. Cheers.
