### ISSUE TITLE
OpenTheme link in list is broken

### ISSUE THREAD

**Issue by gynter** [mattvh/jekyllthemes#147]
Correct would be <http://jekyllthemes.org/themes/opentheme%20copy/>

**Comment by geraldb** [comment]
@gynter  I invite you to flag the error at the new alternative Dr. Jekyll's Themes site.  All themes are listed in the [themes.yml](https://github.com/drjekyllthemes/drjekyllthemes.github.io/blob/master/_data/themes.yml) datafile. Any help appreciated. Cheersl

**Comment by gynter** [comment]
@geraldb Thank You for the invite, but I have already a lot of (still uncommited) changes to this repository which I will throw to the PR. Currently I have reviewed over 50% of the themes.

**Comment by geraldb** [comment]
@gynter  - It's up-to-you of course. Good look. Just a friendly reminder that the new "system" in the new repo is way easier - all themes are listed in a single plain text themes.yml file. Ironic, isn't it? Cheers.
