### ISSUE TITLE
Redesign the site

### ISSUE THREAD

**Issue by anandubajith** [mattvh/jekyllthemes#149]
The site's design is outdated.
can we just redeisgn the site.

**Comment by gynter** [comment]
Hello! In my opinion current layout is easy to read and does not contain any fancy-pancy things which would only make the content harder to process. It does exactly what it's ment to do, list the available themes :smile: .

**Comment by mattvh** [comment]
100% in agreement with @gynter. The site does what it's meant to, looks decent, and doesn't need to follow whatever the latest trend-of-the-month is.
