### ISSUE TITLE
Hosting, building, and contributing

### ISSUE THREAD

**Issue by gynter** [mattvh/jekyllthemes#188]
@mattvh You mentioned that You'd need to fix the building scripts to add me as contributor to this project. Is there any paticular reason You are self hosting jekyllthemes.org instead of using Github pages?

**Comment by mattvh** [comment]
I've got that taken care of the build script issue for now. (It was a minor issue with permissions that arose after some changes.) I use my own server primarily for two reasons: 1. It keeps the door open to use Jekyll plugins if needed, which GitHub doesn't allow. 2. While I like GitHub, I don't want to be tied to it for any of my projects. Git is, after all, meant to be distributed, and I'd like to have it be easy to jump ship (without having to deal with hosting changes) if the need ever arises.

Now, about contributing...

You've been doing great work here these last few weeks, processing submissions and such. I'm going to go ahead and add you as a project contributor and hopefully we'll be able to keep the PR queue down better.

Currently, I'm using manual git deployment for the site, so I'll have to push the changes to the server myself, but I'll probably look into setting up something that ties into GitHub's webhooks eventually to streamline the process.
