### ISSUE TITLE
hi,I'm here

### ISSUE THREAD

**Issue by Richardphp** [mattvh/jekyllthemes#201]
Just leave a message.

**Comment by mushishi78** [comment]
Hey Richard.

**Comment by Richardphp** [comment]
hi,how are you. where are you? This is in Guanghzhou ,China.

**Comment by mushishi78** [comment]
I'm alright. I'm in Brockenhurst, UK.

I'm not sure the maintainer of this project will appreciate chit chat on this thread.

**Comment by Richardphp** [comment]
haha,I don't know.I just have a try using this.
