### ISSUE TITLE
Problems boot server

### ISSUE THREAD

**Issue by evertonl1ma** [mattvh/jekyllthemes#284]
The theme is in trouble when it starts, and ends up not being initialized. By indicating the error is in .sass files

**Comment by gynter** [comment]
@evertonl1ma Didn't understand You correctly, please elaborate.

**Comment by evertonl1ma** [comment]
I can not climb the server.
You can not use, it is full of problems.

**Comment by gynter** [comment]
I still cannot understand what You exactly mean.
