### ISSUE TITLE
Thunder heme not showing up

### ISSUE THREAD

**Issue by sharu725** [mattvh/jekyllthemes#346]
Hi, Looks like the commits are merged but thunder theme isn't showing up on the list.

**Comment by gynter** [comment]
I'll try to review all new themes this week.

**Comment by sharu725** [comment]
Any update?

**Comment by gynter** [comment]
Sorry, I was ill. I'll try to check it asap.

**Comment by sharu725** [comment]
No problem @gynter . I found it on the 11th page. Thanks for the merge. But not sure why it went to the 11th page. I was hoping the posts are arranged date wise.

**Comment by gynter** [comment]
If it went to wrong page then please see if the date in filename and in front matter are correct.
