### ISSUE TITLE
Why there is no response

### ISSUE THREAD

**Issue by mnichangxin** [mattvh/jekyllthemes#365]
Hello, I submitted a theme, but there has been no response, I hope you can reply, thank you!

**Comment by nikrich** [comment]
@mnichangxin  The first time I submitted a theme it took a day or so to get merged, now I've been waiting for almost a month..

**Comment by gynter** [comment]
I am truly sorry about the hold up. It has been crazy busy summer for me and nearly all of my development projects are on hold. I'll try to look trough all PRs in next 5 days.

**Comment by nikrich** [comment]
@gynter No problem. Thank you for the response

**Comment by gynter** [comment]
And yet again I failed to deliver. Hopefully weekend brings better news. I'm really sorry!

**Comment by dkbm** [comment]
No worries - we appreciate your work for the community!

**Comment by gynter** [comment]
Okay, should be better now. Merged bunch of PRs ;)

**Comment by nikrich** [comment]
@gynter Thaaanks! :)
