### ISSUE TITLE
Advertisement

### ISSUE THREAD

**Issue by scottgallant** [mattvh/jekyllthemes#470]
I'm wondering about advertising our Jekyll CMS (https://forestry.io) on jekyllthemes.org. @mattvh, let me know if you're open to that. If so, you can email me at scott@forestry.io.

**Comment by gynter** [comment]
Hello! Since the site is oriented to free and open source themes the current policy has been not to link to commercial sites.

**Comment by scottgallant** [comment]
Hi @gynter, I see a banner on the top of the page, so it looks like you support advertising now.

Perhaps we could just sponsor the site and cover your hosting costs?  Email me at scott@forestry.io if that could work. Thanks.
