### ISSUE TITLE
Missing Garth theme from site

### ISSUE THREAD

**Issue by daviddarnes** [mattvh/jekyllthemes#494]
Back in May I submitted pull #454, which was later merged. However I can't see the result on the site? Is there a certain order to how themes are added? Doing a site wide search using Google doesn't return anything for Garth (the theme I submitted) https://www.google.co.uk/search?q=site%3Ajekyllthemes.org+garth&oq=site%3Ajekyllthemes.org+garth&aqs=chrome..69i57j69i58.4708j0j4&sourceid=chrome&ie=UTF-8

Can someone look into this?

**Comment by RioSatria** [comment]
The reason your theme doesn't show is because the GitHub Pages fail to built.

I've done two little fixes to ensure that the site are building on my machine:
https://github.com/mattvh/jekyllthemes/pull/498
https://github.com/mattvh/jekyllthemes/pull/497

**Comment by daviddarnes** [comment]
Awesome thanks @RioSatria do I need to make any new PRs for this? Or will it be fixed once these changes are made and built?

**Comment by RioSatria** [comment]
No, you don't have to do anything.
We just need to wait for my fixes to be merged.

**Comment by jarrekk** [comment]
Hi, since we haven't seen this repository's owner for a very long time, I forked it to my [repo](https://github.com/jarrekk/jekyll-theme) and built this website with a new **domain name**:
 <http://jekylltheme.org>.

Anyone's theme who submitted it before will still be seen at <http://jekylltheme.org> and welcome everyone to contribute this website if you have nice themes.

Later I will beautify this repository to make it better, an excellent website needs everyone's contribution/PR too!😊

**Comment by daviddarnes** [comment]
@jarrekk could you at least apply the fixes from this repo? In this case Garth still isn't visible http://jekylltheme.org/themes/garth/

**Comment by jarrekk** [comment]
@daviddarnes I looked up theme **garth** in this [repo](https://github.com/jarrekk/jekyll-theme) but couldn't find it, maybe this theme wasn't merged into this repo, I think you should try to make a new PR to new [repo](https://github.com/jarrekk/jekyll-theme), thanks.

**Comment by daviddarnes** [comment]
@jarrekk I thought your repo was a fork? the theme is here in this repo https://github.com/mattvh/jekyllthemes/blob/master/_posts/2017-03-28-garth.markdown

**Comment by jarrekk** [comment]
@daviddarnes Sorry, my repo was several commits behind mattvh's, now new themes including your theme **Garth** are displaying at <http://jekylltheme.org>, thanks:)
