### ISSUE TITLE
Broken themes

### ISSUE THREAD

**Issue by GromNaN** [mattvh/jekyllthemes#65]
Hello,

First, thanks for creating this very useful index of jekyll themes.
Unfortunately, some of them are broken:

* http://jekyllthemes.org/themes/squared/
* http://jekyllthemes.org/themes/hmfaysal-theme/
* http://jekyllthemes.org/themes/herringcove-theme/

**Comment by nmenag** [comment]
resolve #135

**Comment by gynter** [comment]
The downloads for those have been fixed. Only demo is missing for HMFAYSAL, and it's referred in #155. Please close the issue.
