### ISSUE TITLE
rdiscount problems

### ISSUE THREAD

**Issue by mareekkk** [mattvh/jekyllthemes#731]
**UPDATE: 

It's all okay now.**

Hi,

I received the following error:

`E:\sites\jekyllthemes>jekyll serve
Configuration file: E:/sites/jekyllthemes/_config.yml
            Source: E:/sites/jekyllthemes
       Destination: E:/sites/jekyllthemes/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Markdown processor: "rdiscount" is not a valid Markdown processor.
                    Available processors are: kramdown

  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2016-09-01-zebra.markdown':
                    Invalid Markdown processor given: rdiscount
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid Markdown processor given: rdiscount
                    ------------------------------------------------
      Jekyll 4.1.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------`

Any suggestions?

**Comment by mattvh** [comment]
Not able to check at the moment, but I think we might be on Jekyll 3.x still. I'm guessing rdiscount support is deprecated in the newer one.

**Comment by mareekkk** [comment]
> Not able to check at the moment, but I think we might be on Jekyll 3.x still. I'm guessing rdiscount support is deprecated in the newer one.

Yeah I thought so.
