### ISSUE TITLE
Long pending merge requests. Is JekyllThemes alive?

### ISSUE THREAD

**Issue by manavsehgal** [mattvh/jekyllthemes#84]
Hi @mattvh 

There seem to be long pending merge/pull requests dating back +2 months on JekyllThemes. 

I am wondering if JekyllThemes is alive as a project?

Why don't you seek help from community to keep it current and updated? Or, please consider transferring the project to an active GitHub contributor/maintainer. Maybe https://github.com/jekyll/themes-site (@parkr)... 

I can offer to help either way to grow Jekyll Themes community.

Cheers,
@manavsehgal

**Comment by mattvh** [comment]
Sorry, I let it run a little long this time. Usually I merge and deploy in batches, and I ignored GitHub over the extended holiday season. (Plus, there were one or two pending thumbnail changes.) Should be caught up now.

As for parkr's thing, there's an [open issue](https://github.com/mattvh/jekyllthemes/issues/34) about that. I'm not necessarily opposed to the Jekyll project "taking over" with an official themes.jekyllrb.com in the future, but I don't think that's a priority for the project at the present.

**Comment by manavsehgal** [comment]
Thanks @mattvh - agree that themes.jekyllrb.com does not seem to be a priority. Let's make JekyllThemes the best themes resource there is for GitHub community in the meantime.
